### ISSUE TITLE
A better alternative to guard

### ISSUE THREAD

**Issue by Chewie** [haskelllive/haskelllive#13]
Hello,

I saw you used guard to watch for file save to run the compilation, with the aim of detecting syntax errors.
Might I suggest you the [syntastic](https://github.com/scrooloose/syntastic) plugin? It runs a syntax check on each save, and even highlight the errors in your file and put the errors in a location list!

I think it may interest you.

On an unrelated note, I really enjoyed your first video, I'm looking forward to seeing more!

**Comment by reinh** [comment]
I do use Syntastic, but I also like seeing the compiler errors in their own pane. Thanks for the suggestion!
