### ISSUE TITLE
showSquare bug?

### ISSUE THREAD

**Issue by PatrickLerner** [haskelllive/haskelllive#17]
There is a bug in the showSquare function:

```
showSquare :: Square -> Char
showSquare = maybe '.' showPiece
```

`maybe '.' showPiece` should not work correctly in the current version because empty squares are represented as `(Just Nothing)` not as `Nothing`.

**Comment by jgeralnik** [comment]
The functions that dealt with empty squares as (Just Nothing) dealt with Maybe Squares. showSquare is getting a Square itself, so Nothing still represents an empty square.

**Comment by reinh** [comment]
Thanks, @jgeralnik.
