### ISSUE TITLE
Vim color scheme

### ISSUE THREAD

**Issue by clementi** [haskelllive/haskelllive#18]
The color schemes in Episodes 1 and 2 are different. Which one is in use in Episode 1, and which one is in use in Episode 2?

**Comment by reinh** [comment]
Episode 1 is [Solarized](http://ethanschoonover.com/solarized)

Episode 2 is [Tomorrow Night Bright](https://github.com/chriskempson/tomorrow-theme/) with some minor additions for Haskell that I still need to contribute upstream. :(
