### ISSUE TITLE
Scala Offshoot

### ISSUE THREAD

**Issue by jamesthompson** [haskelllive/haskelllive#19]
Hi guys,

I'm new to Haskell but absolute loving it! I thought I'd try to translate the ideas on this series into Scala as an exercise for learning. 

Please check out my offshoot on Github :

https://github.com/jamesthompson/Chess

Let me know what you think on my issues or fork or whatever!

I think it's amazing how much Scala has borrowed from prior art in functional languages, there's so many similarities between Haskell and Scala.

**Comment by reinh** [comment]
Very cool!

**Comment by jamesthompson** [comment]
Thanks! Can't wait for the next episode!
