### ISSUE TITLE
Control.Error.Util

### ISSUE THREAD

**Issue by schell** [haskelllive/haskelllive#21]
Forgive me if this is inappropriately noobish, but ghc seems to be complaining about Control.Error.Util: 

```
error | Could not find module `Control.Error.Util'
```

Is this a module I have to install with cabal? I can't seem to find 'note' on hoogle...

**Comment by anund** [comment]
The package is called "errors" and you can use cabal to get it.

**Comment by schell** [comment]
Thanks!
