### ISSUE TITLE
import Control.Error.Util (note) No longer works (Control.Error.Util DNE). Where is note now?

### ISSUE THREAD

**Issue by hawkins** [haskelllive/haskelllive#24]
Looks like the `Control.Error.Util` package does not exist anymore, and I can't determine where it was moved to. How would one import the `note` function now?

**Comment by edouardpoitras** [comment]
You need the 'errors' package:
`cabal install errors`

**Comment by hawkins** [comment]
Thanks, looks like that'll fix it. For anyone looking at this in the future, here's the documentation on the module in case its lost later: https://hackage.haskell.org/package/errors-2.1.3/docs/Control-Error-Util.html
