### ISSUE TITLE
A tool for pregenerating tests

### ISSUE THREAD

**Issue by mnrk** [haskelllive/haskelllive#4]
Hi, I have noticed that when your video started, it looked like you had pregenerated a blank test case. Is this some snippet in Vim, or is it some kind of a tool that can automatically generate test stubs once you create a new file?

Looking forward to future episodes, good job, man!

**Comment by tobiassjosten** [comment]
I also noticed that and got curious.

Would be nice to see some more focus on testing overall. Like how you asserted the showBoard/readBoard equality — maybe that could have been moved to a test case?

**Comment by reinh** [comment]
@janminarik That's just a template that I automatically load when I create a new Haskell buffer using @tpope's (old but still usable) [ztemplate](http://tpope.us/cgi-bin/cvsweb/~checkout~/tpope/.vim/plugin/ztemplate.vim).

@tobiassjosten You're right! I plan on incorporating Hunit and QuickCheck starting with Episode 3! I might also switch to [Test.Framework](http://hackage.haskell.org/packages/archive/test-framework/latest/doc/html/Test-Framework.html).

**Comment by benjaminfjones** [comment]
The ztemplate link above is broken. Here is a valid one:

https://github.com/tpope/tpope/blob/master/.vim/plugin/ztemplate.vim
