### ISSUE TITLE
Split Screen

### ISSUE THREAD

**Issue by ShaneHudson** [haskelllive/haskelllive#5]
Hey,

Great tutorial! Not quite to do with the tutorial but I was wondering how you managed to split the window? I know how to do it in vim but not standalone to compile.

Thanks,
Shane

**Comment by BrianHicks** [comment]
It looks like he was using tmux. It's like screen.

EDIT: "It's like screen." is a massive understatement. But it can do the same things.

**Comment by reinh** [comment]
Yep, vim inside tmux. I'll be posting a video describing the setup soon.
