### ISSUE TITLE
On the bottom right you have an application "guard" - what is it?

### ISSUE THREAD

**Issue by Egwor** [haskelllive/haskelllive#8]
What's the application? I've googled for it but still can't find it!

**Comment by tobynet** [comment]
Hi, Egwor.

I think "guard" is this https://github.com/guard/guard

> Guard is a command line tool to easily handle events on file system modifications.

You can find a setting of guard for this live https://github.com/haskelllive/haskelllive/blob/master/Guardfile

In this live, I guessed that when a coder saves a source file, then "runghc" runs automatically.

**Comment by Egwor** [comment]
that's perfect, thanks! [you have to install both guard and the guard-shell gems though]
