### ISSUE TITLE
cheezy porn music

### ISSUE THREAD

**Issue by jei731** [haskelllive/haskelllive#9]
You might want to either reconsider the cheezy porn music beginning, or include it in the entire episode and include some hot breathing as the code begins to compile and gets bigger...

**Comment by ocharles** [comment]
Personally I think the music is fine, and I would rather you focus on the content of these episodes.

**Comment by blam23** [comment]
On a side note, could you either make the music at the start of each video quieter while you talk, or fade it off earlier before you start talking?

Thanks :)

**Comment by reinh** [comment]
I like the music, so you're just going to have to deal with it. I will, however, make it quieter so you can hear my awesome voice more clearly. Oh also @jei731 next time you might want to try not being a dick about it.
